### ISSUE TITLE
data loss when expiring snapshots

### ISSUE THREAD

**Issue by dustin** [duckdb/ducklake#527]
### What happens?

I was expiring some snapshots and lost some live tables.  I've attempted a repro and lost some rows, but not the entire tables.

I'm not 100% sure what the state of the dropped table was, but I remember renaming a table at some point in the past, so it's possible there was a rename.  That reproduced the issue locally.

### To Reproduce

```
D create table a(i uuid);
D insert into a values(uuidv7());
D alter table a rename to b;
D insert into b values(uuidv7());
D select * from b;
┌──────────────────────────────────────┐
│                  i                   │
│                 uuid                 │
├──────────────────────────────────────┤
│ 019a0922-0aca-739c-99e2-cefe27580000 │
│ 019a0922-2257-7683-a975-22a15cc3accd │
└──────────────────────────────────────┘
D call ducklake_expire_snapshots('lake', older_than => now() - INTERVAL '1 second');
┌─────────────┬──────────────────────┬────────────────┬───┬─────────┬────────────────┬───────────────────┐
│ snapshot_id │    snapshot_time     │ schema_version │ … │ author  │ commit_message │ commit_extra_info │
│    int64    │ timestamp with tim…  │     int64      │   │ varchar │    varchar     │      varchar      │
├─────────────┼──────────────────────┼────────────────┼───┼─────────┼────────────────┼───────────────────┤
│           0 │ 2025-10-21 13:36:5…  │              0 │ … │ NULL    │ NULL           │ NULL              │
│           1 │ 2025-10-21 13:36:5…  │              1 │ … │ NULL    │ NULL           │ NULL              │
│           2 │ 2025-10-21 13:36:5…  │              1 │ … │ NULL    │ NULL           │ NULL              │
│           3 │ 2025-10-21 13:37:0…  │              2 │ … │ NULL    │ NULL           │ NULL              │
├─────────────┴──────────────────────┴────────────────┴───┴─────────┴────────────────┴───────────────────┤
│ 4 rows                                                                             7 columns (6 shown) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
D select * from b;
┌────────┐
│   i    │
│  uuid  │
├────────┤
│ 0 rows │
└────────┘
```

### OS:

MacOS 26

### DuckDB Version:

DuckDB v1.4.1 (Andium) b390a7c376

### DuckLake Version:

d7f7908

### DuckDB Client:

CLI

### Full Name:

Dustin Sallings

### Affiliation:

Hobbiest

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by guillesd** [comment]
Hi @dustin I see that you opened several issues that I feel are very similar. I think most have in common that an alter table operation is done and then snapshots are expired, and somehow DuckLake looses track of this schema changes. I'm gonna forward just one of them and keep the other open for now for reference, but they all might point to the same underlying issue.

Thanks!

**Comment by dustin** [comment]
Yeah, they're different test cases, at least, but I don't have enough familiarity with the code to know how many problems it is.  It does feel like it could be a single area that might not be too hard to fix, I hope.

After I ran into the table disappearing on an instance I'm using, I made it easy to reproduce this class of problem, though.

Thanks for looking into this.

**Comment by pdet** [comment]
Thanks for creating the issue!

Should be fixed by #543 

Feel free to reopen if the issue happens again!

**Comment by djouallah** [comment]
in my case, I don't care about time travel and want only to keep the latest snapshot, i added those option, when I run checkpoint, all the data was deleted :)

```
CALL set_option('expire_older_than', '0 hour');  
CALL set_option('delete_older_than', '0 hour'); 
```
i thought the latest snapshot will be protected regardless of any option I did ? is this how it is supposed to work

**Comment by dustin** [comment]
Are you running a recent version?  As far as I can tell, the issue has been fixed.

**Comment by djouallah** [comment]
i am, so just to confirm, to keep only the latest active snapshot, all you need is to pass 0 hour as the value, right ?

**Comment by dustin** [comment]
If you look at the original bug report, there are a few things that might help:

1. The specific ducklake version you're running.
2. The code required to reproduce your error.

Perhaps in a new bug report since the repro for the issue here was verified and fixed.

Not trying to be annoying, but it's still not clear you're running a fixed version or that you're doing something that isn't expected to end up with the results you're not expecting.

**Comment by djouallah** [comment]
@dustin thanks,  i will open a new bug report, but my question is about the expected behavior, I don't know if there is a way to tell ducklake keep only 1 active snapshot, basically I don't know if it should be a bug or feature request

**Comment by dustin** [comment]
ducklake shouldn't delete any active data.  i.e., a non-time-travel query run before and after an `expire_older_than` call should return the same results (assuming no other modifications happening between them).

From that perspective, there's really no difference between my "1 second" and your "0 hour".
